### ISSUE TITLE
v1.1.2 bug

### ISSUE THREAD

**Issue by 2yung** [jcasbin/jdbc-adapter#2]
code:  "?rewriteBatchedStatements=true".
It should be like this:

```java
if url.contains("?"){
    url = url + "&rewriteBatchedStatements=true";
}else {
    url = url + "?rewriteBatchedStatements=true";
}
```

**Comment by hsluoyz** [comment]
Hi @2yung , I didn't understand your question. Can you provide more details? Is this issue about the core jCasbin or this JDBC adapter? If it's about jCasbin, please ask question there.

**Comment by 2yung** [comment]
jdbc adapter 最新提交里面修改的那两行，如果我传的url参数里面已经包含了问号，就有问题了

**Comment by hsluoyz** [comment]
@2yung would you please modify your text into English? I want this conversation to be useful for audience from all countries.

**Comment by hsluoyz** [comment]
Closed as stale.

**Comment by chengzime** [comment]
这个问题我也遇到了, 在最新版本中依然存在这个问题: 
(I also encountered this problem, which still exists in the latest version:)
```
<dependency>
            <groupId>org.casbin</groupId>
            <artifactId>jdbc-adapter</artifactId>
            <version>1.1.3</version>
        </dependency>
```
在引入这个包的时候, 如果按照官方示例
(When introducing this package, follow the official example)
```
JDBCAdapter a = new JDBCAdapter("com.mysql.cj.jdbc.Driver", "jdbc:mysql://localhost:3306/", "root", "123");
或者
JDBCAdapter a = new JDBCAdapter("com.mysql.cj.jdbc.Driver", "jdbc:mysql://localhost:3306/casbin", "root", "123", true);
```
会抛出异常
(It throws an exception)
```
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.casbin.adapter.JDBCAdapter.open(JDBCAdapter.java:109)
	at org.casbin.adapter.JDBCAdapter.<init>(JDBCAdapter.java:85)
	at cn.com.chengzi.access.control.domain.JCasbinTest.main(JCasbinTest.java:18)
Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value '�й���׼ʱ��' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
	at com.mysql.cj.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:132)
	at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2139)
	at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2163)
	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1301)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:860)
	... 9 more
Exception in thread "main" java.lang.NullPointerException
	at org.casbin.adapter.JDBCAdapter.createTable(JDBCAdapter.java:134)
	at org.casbin.adapter.JDBCAdapter.open(JDBCAdapter.java:120)
	at org.casbin.adapter.JDBCAdapter.<init>(JDBCAdapter.java:85)
	at cn.com.chengzi.access.control.domain.JCasbinTest.main(JCasbinTest.java:18)
```
显然, 我们需要添加时区配置
(Obviously, we need to add time zone configuration)
修改完成的配置如下:
(The configuration that is modified is as follows:)
```
JDBCAdapter a = new JDBCAdapter("com.mysql.cj.jdbc.Driver", "jdbc:mysql://localhost:3306/casbin?serverTimezone=UTC", "root", "123", true);
```
此时, 会抛出一个此 `issues` 发起者所描述的异常
(At this point, an exception described by the originator of `issues` is thrown)
```
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:897)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:822)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:447)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.casbin.adapter.JDBCAdapter.open(JDBCAdapter.java:109)
	at org.casbin.adapter.JDBCAdapter.<init>(JDBCAdapter.java:85)
	at cn.com.chengzi.access.control.domain.JCasbinTest.main(JCasbinTest.java:18)
Caused by: com.mysql.cj.exceptions.WrongArgumentException: No timezone mapping entry for 'UTC?rewriteBatchedStatements=true'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
	at com.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2153)
	at com.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2163)
	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1301)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:860)
	... 9 more
Exception in thread "main" java.lang.NullPointerException
	at org.casbin.adapter.JDBCAdapter.createTable(JDBCAdapter.java:134)
	at org.casbin.adapter.JDBCAdapter.open(JDBCAdapter.java:120)
	at org.casbin.adapter.JDBCAdapter.<init>(JDBCAdapter.java:85)
	at cn.com.chengzi.access.control.domain.JCasbinTest.main(JCasbinTest.java:18)
```
代码中没有判断 `url` 中是否已经存在 `?`, 导致配置错误
(Does the code not determine whether 'already exists in' url '? ', resulting in configuration error)

**Comment by hsluoyz** [comment]
Hi @chengzime  please modify your comments into English only as we are an English-lang community.
