### ISSUE TITLE
Broken connection not re-established.

### ISSUE THREAD

**Issue by lanmarti** [jcasbin/jdbc-adapter#32]
I've got a jcasbin setup with a JDBC adapter connecting to postgres. Both the jcasbin setup and the postgres are running as containers in separate Kubernetes pods.
If the Postgres pod goes down and is restarted, the next call from the adapter fails with:
```
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO casbin_rule (ptype,v0,v1,v2,v3,v4,v5) VALUES(*[SNIP]*) was aborted: An I/O error occurred while sending to the backend.  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:145)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:486)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:840)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1538)
        at org.casbin.adapter.JDBCBaseAdapter.addPolicy(JDBCBaseAdapter.java:317)
        at org.casbin.adapter.JDBCAdapter.addPolicy(JDBCAdapter.java:36)
        at org.casbin.jcasbin.main.InternalEnforcer.addPolicy(InternalEnforcer.java:41)
        at org.casbin.jcasbin.main.ManagementEnforcer.addNamedPolicy(ManagementEnforcer.java:303)
        at org.casbin.jcasbin.main.ManagementEnforcer.addPolicy(ManagementEnforcer.java:267)
        at org.casbin.jcasbin.main.ManagementEnforcer.addPolicy(ManagementEnforcer.java:290)
*[SNIP]*
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
        ... 19 more
Caused by: java.io.EOFException
        at org.postgresql.core.PGStream.receiveChar(PGStream.java:308)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1952)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:481)
        ... 18 more
```

Any subsequent calls fail with:
```
Stacktrace: org.apache.felix.log.LogException: java.lang.Error: org.postgresql.util.PSQLException: This connection has been closed.
        at org.casbin.adapter.JDBCBaseAdapter.addPolicy(JDBCBaseAdapter.java:320)
        at org.casbin.adapter.JDBCAdapter.addPolicy(JDBCAdapter.java:36)
        at org.casbin.jcasbin.main.InternalEnforcer.addPolicy(InternalEnforcer.java:41)
        at org.casbin.jcasbin.main.ManagementEnforcer.addNamedPolicy(ManagementEnforcer.java:303)
        at org.casbin.jcasbin.main.ManagementEnforcer.addPolicy(ManagementEnforcer.java:267)
        at org.casbin.jcasbin.main.ManagementEnforcer.addPolicy(ManagementEnforcer.java:290)
*[SNIP]*
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.felix.log.LogException: org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
        at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1680)
        at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:371)
        at org.casbin.adapter.JDBCBaseAdapter.addPolicy(JDBCBaseAdapter.java:306)
        ... 15 more
```

After restarting the casbin setup, everything works as expected again. Could the error handling be changed so that the adapter attempts to reconnect in case of a closed connection, instead of immediately having an unrecoverable state?

**Comment by shy1st** [comment]
Maybe we should provide a datasource connection function which can set the interval and the number of retries.
@hsluoyz What do you think about it?

**Comment by hsluoyz** [comment]
@shy1st no need to provide option. We can always try best to deliver: always attempts to reconnect when disconnected

**Comment by hsluoyz** [comment]
@seriouszyx plz work on this issue as next step
